# Generated by Django 4.1.7 on 2023-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('password', models.CharField(max_length=25, verbose_name='Пароль')),
            ],
        ),
    ]
